[tool.poetry]
name = "tap-netsuite"
version = "2.3.0"
description = "Singer.io tap for extracting data for NetSuite"
authors = ["Stitch"]
classifiers = ["Programming Language :: Python :: 3 :: Only"]

[tool.poetry.dependencies]
python = "^3.13.0"
netsuitesdk = {git = "ssh://git@github.com/symon-ai/netsuite-sdk-py.git", tag = "v3.0.0"}

requests = "^2.33.0"
singer-python = "6.3.0"
jsonpath-ng = "^1.5.3"
lxml = "^6.1.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
tap-netsuite = "tap_netsuite:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
